// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://vefgzorseudueesyhwmb.supabase.co'; //import.meta.env.VITE_SUPABASE_URL || 'https://your-project.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZmd6b3JzZXVkdWVlc3lod21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNzIzNjIsImV4cCI6MjA2NTk0ODM2Mn0.qeBQGXMu_sJwgU2vhfOkcBKlaXMlAE2s0gdX4INdJak'; //import.meta.env.VITE_SUPABASE_ANON_KEY || 'your-anon-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);